package com.muthukumarasamym.leetcode;

import java.util.Scanner;

public class FindDifference {
	
	       //String t is generated by random shuffling string s and then add one more letter at a random position.

	public static void main(String[] args) {
		Scanner mc= new Scanner(System.in);
		System.out.println("Enter the string1");
		String s=mc.nextLine();
		System.out.println("Enter the string2");
		String t=mc.nextLine();
		System.out.println(findTheDifference(s,t));

	}

	private static char findTheDifference(String s, String t) {
		
		char k=0;
		for(char c:s.toCharArray())
		{
			k^=c;
			System.out.println((char)k);
		}
		System.out.println((char)k);
		for(char c:t.toCharArray())
			k^=c;
		System.out.println((char)k);
		return 'a';
		
	}

}
